### ISSUE TITLE
AdMobYandexMobileAdsAdapters blocks the use of the new version of YandexMobileAds 5.8.0

### ISSUE THREAD

**Issue by SanatzhanAimukambetov** [yandexmobile/yandex-ads-sdk-ios#163]
Error when trying to update YandexMobileAds 5.7.0 -> 5.8.0 in order to fix crashes that you [reported](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/160).
![Снимок экрана 2023-07-04 в 10 21 46](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/73227374/b42e023f-32dd-4b82-9e75-cee480a51161)
Any feedback and progress on this issue will be very grateful. Thank you in advance.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25009838. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp04.07.2023, 07:25, "Sanatzhan Aimukambetov" ***@***.***>:
Error when trying to update YandexMobileAds 5.7.0 -> 5.8.0 in order to fix crashes that you reported.

Any feedback and progress on this issue will be very grateful. Thank you in advance.

**Comment by SanatzhanAimukambetov** [comment]
Получилось обновить убрав версию у AdMobYandexMobileAdsAdapters и вызва

**Comment by SanatzhanAimukambetov** [comment]
Resolved by removing exact version for AdMobYandexMobileAdsAdapters and calling pod update
