### ISSUE TITLE
Upload Archive Error

### ISSUE THREAD

**Issue by ArseniLaputska** [yandexmobile/yandex-ads-sdk-ios#206]
Доброго времени! При попытке отправить архив в TestFlight выдает следующие ошибки
<img width="704" alt="Screenshot 2024-03-21 at 5 55 04 PM" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/69910183/e3c8d35a-d378-4971-af06-a3f0122a3feb">

Устанавливал бибилотеку через SPM. Минимальный таргет iOS 16.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3056. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3056 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by ArseniLaputska** [comment]
P.S. Обошел данную ошибку установкой библиотеки через Cocoapods. Но я думаю было бы круто узнать причину, тк все остальные зависимости через SPM используются.

**Comment by Spetruk** [comment]
Уже апрель, а проблема осталась

**Comment by mobile-ads-github** [comment]
Во фрэймворке поменялся формат версий в `Info.plist`

Подобные ишью:
* [empty field MinimumOSVersion for internal FB frameworks causes failure on uploading to App Store Connect with Xcode 15.3](https://github.com/firebase/firebase-ios-sdk/issues/12475)
* [App archive fails validation due to invalid plist file](https://github.com/firebase/firebase-ios-sdk/issues/12441)
* [App archive fails validation due to invalid plist file on Xcode 15.3](https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263)


До исправления с нашей стороны, это можно исправть вручную:

* В Xcode выбрать Window > Organizer > Archives > Для нужной вресии выбрать `Show In Finder`

<img width="1025" alt="Screenshot 2024-04-22 at 10 26 11" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/31896236/9a553d84-f84a-46f0-afa2-71429044b224">

* Перейти в Products > Applications > Right click on your app and select `Show Package Contents` > Frameworks > `YandexMobileAds.framework` > Info.plist

* Найти опцию `MinimuOSVersion` и заменить ее на`130.0`

Для `YandexMobileAdsInstream.framework` проделать то же самое
